services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - CADDY_ADMIN_URL=http://caddy:2019
      - BUILDKIT_HOST=tcp://buildkit:1234
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATABASE_URL=postgresql://hangar:hangar@postgres:5432/hangar
      - REDIS_URL=redis://redis:6379
      - NOMAD_ADDR=http://host.docker.internal:4646
      - CONSUL_ADDR=http://host.docker.internal:8500
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      caddy:
        condition: service_started
      buildkit:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    extra_hosts:
      - "host-gateway:172.30.186.74"
      - "host.docker.internal:host-gateway"

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data

  buildkit:
    image: moby/buildkit
    privileged: true
    restart: unless-stopped
    command: --addr tcp://0.0.0.0:1234 --oci-worker-snapshotter=overlayfs
    volumes:
      - buildkit-cache:/var/lib/buildkit

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hangar
      POSTGRES_USER: hangar
      POSTGRES_PASSWORD: hangar
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hangar" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data

volumes:
  caddy-data:
  buildkit-cache:
  pg-data:
  redis-data:
