[nomad_servers]
localhost ansible_connection=local

[nomad_clients]

[hangar:children]
nomad_servers
nomad_clients

[nomad_servers:vars]
nomad_server_count=1

[nomad_clients:vars]
nomad_server_count=0
